#!/bin/sh

TDM="$(command -v tdm)"
AWE="$(command -v awesome)"
XFCE4="$(command -v startxfce4)"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -n "$TDM" ]; then
  exec "$TDM" --xstart
elif [ -n "$AWE" ]; then
  exec "$AWE"
elif [ -n "$XFCE4" ]; then
  exec "$XFCE4"
fi
